/* AUTO-GENERATED by update-gallery.ps1 - add or remove photos, then re-run the script. */
window.GALLERY = {
  categories: [
    { id: "remodeling", label: "Remodeling" },
    { id: "painting", label: "Painting" }
  ],
  items: [
    { cat: "remodeling", src: "assets/gallery/remodeling/interior-framing.jpg", title: "Interior Framing", w: 1800, h: 1350 },
    { cat: "remodeling", src: "assets/gallery/remodeling/porch-ceiling.jpg", title: "Porch Ceiling", w: 1200, h: 900 },
    { cat: "painting", src: "assets/gallery/painting/stained-shutters.jpg", title: "Stained Shutters", w: 1200, h: 900 }
  ]
};
