<#
  Project gallery updater
  -----------------------
  1. Put photos in  gallery-inbox\<service>\   (folder name = the filter tab, e.g. roofing, painting, tile)
     Any new folder name becomes a new tab (e.g. gallery-inbox\decks  ->  "Decks").
  2. Run:  powershell -ExecutionPolicy Bypass -File .\update-gallery.ps1
  3. Refresh the site. Done.

  Photos are auto-rotated, shrunk to max 1600px and saved to assets\gallery\<service>\.
  Your originals in gallery-inbox are never changed.
  The file name becomes the caption:  "kitchen-remodel.jpg" -> "Kitchen Remodel".
  Start a name with a number to control order:  "01-kitchen-remodel.jpg".
  To remove a photo, delete it from assets\gallery\<service>\ and run this script again.
#>
$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Drawing

$root     = $PSScriptRoot
$inbox    = Join-Path $root 'gallery-inbox'
$out      = Join-Path $root 'assets\gallery'
$dataFile = Join-Path $root 'gallery-data.js'
$maxSize  = 1280
$standard = 'remodeling', 'roofing', 'painting', 'sheetrock', 'ac', 'tile'
$textInfo = (Get-Culture).TextInfo

foreach ($d in $standard) {
  $p = Join-Path $inbox $d
  New-Item -ItemType Directory -Force $p | Out-Null
  if (-not (Get-ChildItem $p -Force -ErrorAction SilentlyContinue)) { New-Item -ItemType File -Force (Join-Path $p '.gitkeep') | Out-Null }
}
New-Item -ItemType Directory -Force $out | Out-Null

function Get-Slug($s) { ($s.ToLower() -replace '[^a-z0-9]+', '-').Trim('-') }

function Save-Resized($src, $dst) {
  $img = [System.Drawing.Image]::FromFile($src)
  try {
    # Phone photos store rotation in EXIF; apply it so pictures aren't sideways.
    if ($img.PropertyIdList -contains 0x0112) {
      switch ($img.GetPropertyItem(0x0112).Value[0]) {
        3 { $img.RotateFlip('Rotate180FlipNone') }
        6 { $img.RotateFlip('Rotate90FlipNone') }
        8 { $img.RotateFlip('Rotate270FlipNone') }
      }
    }
    $scale = [Math]::Min(1.0, $maxSize / [Math]::Max($img.Width, $img.Height))
    $w = [int]($img.Width * $scale); $h = [int]($img.Height * $scale)
    $bmp = New-Object System.Drawing.Bitmap($w, $h)
    $g = [System.Drawing.Graphics]::FromImage($bmp)
    $g.Clear([System.Drawing.Color]::White)
    $g.InterpolationMode = 'HighQualityBicubic'
    $g.DrawImage($img, 0, 0, $w, $h)
    $g.Dispose()
    $codec = [System.Drawing.Imaging.ImageCodecInfo]::GetImageEncoders() | Where-Object MimeType -eq 'image/jpeg'
    $ep = New-Object System.Drawing.Imaging.EncoderParameters(1)
    $ep.Param[0] = New-Object System.Drawing.Imaging.EncoderParameter([System.Drawing.Imaging.Encoder]::Quality, [long]68)
    $bmp.Save($dst, $codec, $ep)
    $bmp.Dispose()
  } finally { $img.Dispose() }
}

# 1) Process new / changed photos from the inbox
$added = 0
Get-ChildItem $inbox -Directory | ForEach-Object {
  $cat  = Get-Slug $_.Name
  $dest = Join-Path $out $cat
  New-Item -ItemType Directory -Force $dest | Out-Null
  Get-ChildItem $_.FullName -File | ForEach-Object {
    if ($_.Name -eq '.gitkeep') { return }
    if ($_.Extension.ToLower() -notin '.jpg', '.jpeg', '.png') {
      Write-Warning "Skipped $($_.FullName) - use JPG or PNG (iPhone: Settings > Camera > Formats > Most Compatible, or export as JPG)."
      return
    }
    $target = Join-Path $dest ((Get-Slug $_.BaseName) + '.jpg')
    if ((Test-Path $target) -and ((Get-Item $target).LastWriteTime -ge $_.LastWriteTime)) { return }
    Save-Resized $_.FullName $target
    Write-Host "  + $cat / $($_.Name)"
    $script:added++
  }
}

# 2) Rebuild gallery-data.js from whatever is in assets\gallery
function Get-Label($slug) { if ($slug -eq 'ac') { 'AC' } else { $textInfo.ToTitleCase(($slug -replace '-', ' ')) } }
function Js($s) { ($s | ConvertTo-Json -Compress) }

$dirs = Get-ChildItem $out -Directory
$ordered = @($standard | Where-Object { $dirs.Name -contains $_ }) + @($dirs.Name | Where-Object { $standard -notcontains $_ } | Sort-Object)

$cats = @(); $items = @()
foreach ($cat in $ordered) {
  $files = Get-ChildItem (Join-Path $out $cat) -File -Filter *.jpg | Sort-Object Name
  if (-not $files) { continue }
  $cats += "    { id: $(Js $cat), label: $(Js (Get-Label $cat)) }"
  foreach ($f in $files) {
    $img = [System.Drawing.Image]::FromFile($f.FullName); $w = $img.Width; $h = $img.Height; $img.Dispose()
    $title = $textInfo.ToTitleCase((($f.BaseName -replace '^\d+[-_. ]+', '') -replace '[-_]+', ' '))
    $items += "    { cat: $(Js $cat), src: $(Js "assets/gallery/$cat/$($f.Name)"), title: $(Js $title), w: $w, h: $h }"
  }
}

$js = "/* AUTO-GENERATED by update-gallery.ps1 - add or remove photos, then re-run the script. */`n" +
      "window.GALLERY = {`n  categories: [`n" + ($cats -join ",`n") + "`n  ],`n  items: [`n" + ($items -join ",`n") + "`n  ]`n};`n"
[System.IO.File]::WriteAllText($dataFile, $js, (New-Object System.Text.UTF8Encoding($false)))

Write-Host "Done. $added new photo(s) processed, $($items.Count) in the gallery across $($cats.Count) service(s)."
